class UjiPengguna {
    public static void main(String[] args) {
        // Buat objek pengguna dan isi datanya sesuai data uji coba
        // Panggil method tampilInfo
        // Tampilkan demonstrasi tentang konstanta final
        Pengguna baru=new Pengguna();
        baru.umur=25;
        baru.beratBadan=60;
        baru.tinggiBadan=170;
        baru.tampilInfo();

//        baru.faktorAktivitas = 1.5;
    }
}